### ISSUE TITLE
When wrapping on the Map only one Tile is revealed going South

### ISSUE THREAD

**Issue by ohyonghao** [CS300-A-Team/Frupal#21]
It depends on direction.
South, when I hit the North side I see only the Tile the character occupies is revealed.
Going East or West no tiles are revealed the first time, but the second press in that direction all tiles that should have been revealed now are.

**Comment by wollzy** [comment]
Ill take another look at this tonight

**Comment by wollzy** [comment]
Ok I see what I did there

I need 4 more cases in there to account for wrapping on each side.  Adding them in now

**Comment by wollzy** [comment]
Wrapping issues are fixed.
